apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: risk-engine-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: risk-engine-app-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90