apiVersion: v1
kind: ConfigMap
metadata:
  name: risk-engine-cm
data:
  RMQ_HOST: "a75b10a42d54343d5807c33c915d4027-772471113.eu-central-1.elb.amazonaws.com"
  RMQ_PORT: "5672"
  LOG_FORMAT: "[%(levelname)s][%(asctime)s][%(name)s]::%(message)s"
  LOG_LEVEL: "INFO"
  RMQ_CONSUME_REQUESTS_QUEUE: "rest-requests"
  RMQ_CONSUME_REQUESTS_QUEUE_RK: "rest-requests"
  RMQ_EXCHANGE: "risk_exchange"
  RMQ_EXCHANGE_TYPE: 'direct'
  RMQ_RESPONSE_EXCHANGE: "flask_exchange"
  RMQ_METHOD_POST_QUEUE: "risk_engine_post_payments_requests"
  RMQ_METHOD_POST_RK: "post"
  RMQ_METHOD_GET_QUEUE: "risk_engine_get_payments_requests"
  RMQ_METHOD_GET_RK: "get"
  RMQ_UNHANDLED_RK: "undefined"
  RMQ_UNHANDLED_METHODS_QUEUE: "risk_engine_unhandled_rest_methods"
  RMQ_PREFETCH_COUNT: "128"



