apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-engine-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-engine-app
  template:
    metadata:
      labels:
        app: risk-engine-app
    spec:
      containers:
        - name: risk-engine-app
          image: '850414232980.dkr.ecr.eu-central-1.amazonaws.com/myrepo:risk-engine-app-1.0'
          resources:
            limits:
              cpu: "0.2"
              memory: "64Mi"
            requests:
              cpu: "0.2"
              memory: "32Mi"
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: risk-engine-rabbitmq-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: risk-engine-rabbitmq-credentials
                  key: password
