apiVersion: v1
kind: Service
metadata:
  name: flask-wsgi-app-service
spec:
  selector:
    app: flask-wsgi-app
  ports:
    - protocol: TCP
      port: 8192
      targetPort: 8192
  type: LoadBalancer