apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flask-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-flask-proxy
  template:
    metadata:
      labels:
        app: nginx-flask-proxy
    spec:
      containers:
        - name: nginx-flask-proxy
          image: nginx:latest
          resources:
            limits:
              cpu: "0.75"
              memory: "256Mi"
            requests:
              cpu: "0.25"
              memory: "64Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-flask-default-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-flask-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5

      volumes:
        - name: nginx-flask-default-config
          configMap:
            name: nginx-flask-default-config
        - name: nginx-flask-config
          configMap:
            name: nginx-flask-config
