apiVersion: v1
kind: Service
metadata:
  name: nginx-flask-proxy-service
spec:
  selector:
    app: nginx-flask-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
