apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dal-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dal-get-app-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80