apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dal-post-app-deployment

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dal-app-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80