apiVersion: apps/v1
kind: Deployment
metadata:
  name: dal-post-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dal-app
  template:
    metadata:
      labels:
        app: dal-app
    spec:
      containers:
        - name: dal-app
          image: '850414232980.dkr.ecr.eu-central-1.amazonaws.com/myrepo:dal-python-1.0'
          resources:
            limits:
              cpu: "0.8"
              memory: "512Mi"
            requests:
              cpu: "0.4"
              memory: "64Mi"
          env:
            - name: CONSUME_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: dal-cm
                  key: RMQ_METHOD_POST_QUEUE
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dal-credentials
                  key: username
            - name: PGSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dal-credentials
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dal-credentials
                  key: password
            - name: PGSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dal-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: "/k8s_files/dal_cm.yaml"
      volumes:
        - name: config-volume
          configMap:
            name: dal-cm

